[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "cython>=3.0",
    "numpy>=1.21"
]
build-backend = "setuptools.build_meta"

[project]
name = "lens_format"
version = "4.0.1"
requires-python = ">=3.8"
